services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models:ro  # read-only mount
    environment:
      - MODEL_PATH=/app/models/classifier.pkl